# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(help_text='Upload an image', null=True, upload_to='media/'),
        ),
    ]
