# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180320_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(help_text='Upload an image', null=True, upload_to='blog/blog/static/'),
        ),
    ]
